import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/global/navbar";
import Footer from "@/components/global/footer";
import { ray } from "@/next-persian-fonts/ray";

import { Toaster } from "react-hot-toast";
import ChatWidget from "@/components/global/chatWidget";
import FooterMobile from "@/components/global/mobileFooter";
import Head from "next/head";

export const metadata: Metadata = {
  title: "املاک اوج",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <Head>
         <link rel="icon" href="/favicon.ico" sizes="any" />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="48x48"
          href="/favicon-48x48.png"
        />

        {/* Apple Touch Icon */}
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />

        {/* Android / PWA */}
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <body className={ray.className}>
        <Navbar />
        <ChatWidget />
        <Toaster position="top-center" />
        {children}
        <FooterMobile />
        <Footer />
      </body>
    </html>
  );
}
