import type { Metadata } from "next";
// import { Vazirmatn as VazirmatnFont } from "next/font/google";
// import "../styles/leaflet-custom.css";
import "./globals.css";
import Navbar from "@/components/global/navbar";
import Footer from "@/components/global/footer";
import { ray } from "@/next-persian-fonts/ray";

// import Breadcrumb from "@/components/global/breadCrumbs";
import { Toaster } from "react-hot-toast";
import ChatWidget from "@/components/global/chatWidget";
import FooterMobile from "@/components/global/mobileFooter";

// const vazirmatn = VazirmatnFont({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "املاک اوج",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body className={ray.className}>
        <Navbar />
        {/* <SmoothScrollProvider /> */}
        <ChatWidget />
        <Toaster position="top-center" />
        {/* <Breadcrumb /> */}
        {children}
        <FooterMobile />
        <Footer />
      </body>
    </html>
  );
}
